name: Release Workflow
on:
  release:
    types:
      - created
permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo apt install build-essential g++ yasm pkg-config libwxgtk3.0-gtk3-dev libfuse-dev libpcsclite-dev wx3.0-headers
    - name: make
      run: |
        cd ./src
        make -j WXSTATIC=1
    - name: list directory
      run: |
        cd ./src
        ls -R
    - name: Upload release artifact
      uses: svenstaro/upload-release-action@v2
      with:
        file: src/Main/veracrypt
        file_glob: false
        tag: ${{ github.ref }}
        body: |
          ${{ steps.get_release_body.outputs.body }}
        repo_token: ${{ secrets.GITHUB_TOKEN }}
