name: Release Workflow
on:
  release:
    types:
      - created
permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        sudo apt install build-essential g++ yasm pkg-config libfuse-dev libpcsclite-dev
        sudo apt-add-repository 'deb https://repos.codelite.org/wx3.2.0/ubuntu/ jammy universe'
        sudo apt-get update
        sudo apt-get install libwxbase3.2-0-unofficial \
                libwxbase3.2unofficial-dev \
                libwxgtk3.2-0-unofficial \
                libwxgtk3.2unofficial-dev \
                wx3.2-headers \
                wx-common \
                libwxgtk-media3.2-0-unofficial \
                libwxgtk-media3.2unofficial-dev \
                libwxgtk-webview3.2-0-unofficial \ 
                libwxgtk-webview3.2unofficial-dev \ 
                libwxgtk-webview3.2-0-unofficial-dbg \ 
                libwxbase3.2-0-unofficial-dbg \
                libwxgtk3.2-0-unofficial-dbg \
                libwxgtk-media3.2-0-unofficial-dbg \
                wx3.2-i18n \
                wx3.2-examples
    - name: make
      run: |
        cd ./src
        make -j
    - name: list directory
      run: |
        cd ./src
        ls -R
    - name: Upload release artifact
      uses: svenstaro/upload-release-action@v2
      with:
        file: src/Main/veracrypt
        file_glob: false
        tag: ${{ github.ref }}
        body: |
          ${{ steps.get_release_body.outputs.body }}
        repo_token: ${{ secrets.GITHUB_TOKEN }}
