name: Test build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        sudo apt install build-essential g++ yasm pkg-config libfuse-dev libpcsclite-dev libgtk2.0-0 libgtk2.0-dev
        sudo apt-key adv --fetch-keys https://repos.codelite.org/CodeLite.asc
        sudo apt-add-repository 'deb https://repos.codelite.org/wx3.2.0/ubuntu/ jammy universe'
        sudo apt-get update
        sudo apt-get install libwxbase3.2-0-unofficial \
                libwxbase3.2unofficial-dev \
                libwxgtk3.2-0-unofficial \
                libwxgtk3.2unofficial-dev \
                wx3.2-headers \
                wx-common

    - name: make
      run: |
        cd ./src
        git clone https://github.com/wxWidgets/wxWidgets --depth 1 --branch WX_3_0_BRANCH
        ls $(pwd)/wxWidgets
        make WXSTATIC=1 WX_ROOT=$(pwd)/wxWidgets wxbuild
        make -j WXSTATIC=1
